name: Deploy to Lightsail Windows

on:
  push:
    branches:
      - master   # change if you want a different branch

jobs:
  build-and-deploy:
    runs-on: self-hosted   # IMPORTANT: this runs on your Lightsail VM
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4  

      - name: Publish Web API 
        run: dotnet publish ./ISTCOSA/ISTCOSA.csproj -c Release -o ./publish   

      - name: Stop IIS Website
        shell: powershell
        run: |
          $siteName = "elevate-performance"
          Write-Host "Stopping IIS Website: $siteName..."
          & "C:\Windows\System32\inetsrv\appcmd.exe" stop site :"$siteName"         
          Write-Host "Website stopped successfully."
          
    
      - name: Copy files to IIS site
        shell: powershell
        run: |
          robocopy .\publish C:\elevate-performance-api\ *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30 /XF appsettings.json web.config
          $exitCode = $LASTEXITCODE
          Write-Host "Robocopy exit code: $exitCode"
          if ($exitCode -ge 8) { exit $exitCode } else { exit 0 }
          
      - name: Start IIS Website
        shell: powershell
        run: |
          $siteName = "elevate-performance"
          Write-Host "Starting IIS Website: $siteName..."
          & "C:\Windows\System32\inetsrv\appcmd.exe" start site :"$siteName"           
          Write-Host "Website started successfully."
          
