name: Deploy to Lightsail Windows

on:
  push:
    branches:
      - master   # change if you want a different branch

jobs:
  build-and-deploy:
    runs-on: self-hosted   # IMPORTANT: this runs on your Lightsail VM
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4    

      - name: Publish Web API 
        run: dotnet publish ./ISTCOSA/ISTCOSA.csproj -c Release -o ./publish   

      - name: Stop IIS App Pool
        shell: powershell
        run: |
         Import-Module WebAdministration
         $appPool = "Elevate-Performance"
         Write-Host "Stopping App Pool: $appPool..."
         Stop-WebAppPool -Name $appPool
         Start-Sleep -Seconds 5
         Write-Host "App Pool stopped successfully."

          
    
      - name: Copy files to IIS site
        shell: powershell
        run: |
          robocopy .\publish C:\istcosa\
          $exitCode = $LASTEXITCODE
          Write-Host "Robocopy exit code: $exitCode"
          if ($exitCode -ge 8) { exit $exitCode } else { exit 0 }
          
      - name: Start IIS App Pool
        shell: powershell
        run: |
         Import-Module WebAdministration
         $appPool = "Elevate-Performance"
         Write-Host "Starting App Pool: $appPool..."
         Start-WebAppPool -Name $appPool
         Write-Host "App Pool started successfully."

          
